<template>
    <div class="text-center">
        <div
            v-show="show"
            class="loadingio-spinner-double-ring-tc3evlshl9p"
        >
            <div class="ldio-uw8bm97k4no">
                <div></div>
                <div></div>
                <div><div></div></div>
                <div><div></div></div>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import {ref} from 'vue'
interface props{
    show: Boolean
}

const props = defineProps<props>()

</script>

<style type="text/css" scoped>
@keyframes ldio-uw8bm97k4no {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(360deg);
    }
}
.ldio-uw8bm97k4no div {
    box-sizing: border-box !important;
}
.ldio-uw8bm97k4no > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #fef62a transparent #fef62a transparent;
    animation: ldio-uw8bm97k4no 1s linear infinite;
}

.ldio-uw8bm97k4no > div:nth-child(2),
.ldio-uw8bm97k4no > div:nth-child(4) {
    width: 108px;
    height: 108px;
    top: 46px;
    left: 46px;
    animation: ldio-uw8bm97k4no 1s linear infinite reverse;
}
.ldio-uw8bm97k4no > div:nth-child(2) {
    border-color: transparent #140b02 transparent #140b02;
}
.ldio-uw8bm97k4no > div:nth-child(3) {
    border-color: transparent;
}
.ldio-uw8bm97k4no > div:nth-child(3) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}
.ldio-uw8bm97k4no > div:nth-child(3) div:before,
.ldio-uw8bm97k4no > div:nth-child(3) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    background: #fef62a;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #fef62a;
}
.ldio-uw8bm97k4no > div:nth-child(3) div:after {
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #fef62a;
}

.ldio-uw8bm97k4no > div:nth-child(4) {
    border-color: transparent;
}
.ldio-uw8bm97k4no > div:nth-child(4) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}
.ldio-uw8bm97k4no > div:nth-child(4) div:before,
.ldio-uw8bm97k4no > div:nth-child(4) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 30px;
    background: #140b02;
    border-radius: 50%;
    box-shadow: 0 92px 0 0 #140b02;
}
.ldio-uw8bm97k4no > div:nth-child(4) div:after {
    left: -16px;
    top: 30px;
    box-shadow: 92px 0 0 0 #140b02;
}
.loadingio-spinner-double-ring-tc3evlshl9p {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
}
.ldio-uw8bm97k4no {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-uw8bm97k4no div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>